import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import styled from "@emotion/styled";
import Box from "@mui/material/Box";
import { useTheme } from "@emotion/react";

const TagCode = styled.code(({ theme }) => {
  return {
    backgroundColor: theme.palette.background.silver,
    color: theme.palette.text.black,
    borderRadius: "5px",
    padding: "0.75rem",
    fontSize: "1.1rem",
    fontFamily:
      "Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace",
  };
});

const TagSpan = styled.span(({ theme }) => {
  if (theme.palette.mode === "light")
    return {
      height: "1em",
      marginBottom: "0.2em",
      marginLeft: "0.2rem",
    };
  else
    return {
      height: "1em",
      marginBottom: "0.7em",
      marginLeft: "0.5rem",
    };
});

const PillBox = styled(Box)(({ theme }) => {
  if (theme.palette.mode === "dark")
    return {
      background: theme.palette.background.silver,
      padding: "0.2em 0.5em 0.2em 0.2em",
      marginBottom: "0.2em",
      borderRadius: "5px",
    };
});

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing <TagCode>pages/index.js</TagCode>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <TagSpan>
              <PillBox>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </PillBox>
            </TagSpan>
          </a>
        </footer>
      </div>
    </>
  );
}
